### ISSUE TITLE
On Windows, trying to remote debug causes java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#37]
Hi, I'm running the sample on Windows and tried to used the connect option to remotely debug but I'm receiving this error:

java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration

c:\Users\eborisow\workspaces\fusion\connectors-june-2019>gradlew connect

> Task :imap-connector:connect
   -- Using client-jar D:/programs/fusion/4.2.2/apps/connectors/connectors-rpc/client/connector-plugin-client-4.2.2-uberjar.jar
   -- Connecting plugin C:\Users\eborisow\workspaces\fusion\connectors-june-2019\imap-connector\build/libs/imap-connector.zip to localhost:8771
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
        at com.lucidworks.fusion.plugin.handler.ConnectorPluginModuleHandler.<init>(ConnectorPluginModuleHandler.java:185)
        at com.lucidworks.fusion.connector.client.ConnectorClientMain$1.configure(ConnectorClientMain.java:89)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.lucidworks.fusion.connector.client.ConnectorClientMain.<init>(ConnectorClientMain.java:109)
        at com.lucidworks.fusion.connector.client.ConnectorClientMain.loadPlugins(ConnectorClientMain.java:155)
        at com.lucidworks.fusion.connector.client.ConnectorClientMain.main(ConnectorClientMain.java:129)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
After this, the compile just gets stuck in a loop.

Any thoughts?

**Comment by nddipiazza** [comment]
you need to make sure that the classpath of the remote debug session has the complete `apps/connectors/connectors-rpc/libs` as well

**Comment by mwmitchell** [comment]
Hi @eborisowIQVIA. Is this reproducible with the "stock" imap connector from this repo?

**Comment by eborisowIQVIA** [comment]
@nddipiazza- I’ll try that again.  I remember getting it past that error by including all of the jars from /lib but I can’t recall what happened after that.

@mwmitchell-yes, this was using the pull for GitHub running from command line and Eclipse.

**Comment by eborisowIQVIA** [comment]
Once I have it running, what do you do next?  Start the job from Fusion?  Also, do I need to set any additional parameters on the Fusion side?

**Comment by amitmall** [comment]
I am also facing the same issue on mac.

**Comment by mwmitchell** [comment]
We fixed this in a recent release of Fusion 4.2.x - @eborisowIQVIA not sure if you've upgraded, but if so, are there any other remaining/related issues you're having?

**Comment by mwmitchell** [comment]
> I am also facing the same issue on mac.

Hi @amitmall - Assuming you are still experiencing this problem, what version of Fusion are you using?

**Comment by mwmitchell** [comment]
I should've stated this earlier, but the fix for this is in Fusion 4.2.5.

**Comment by mwmitchell** [comment]
Closing... fixed in Fusion 4.2.5
