### ISSUE TITLE
Remote deployment of connectors

### ISSUE THREAD

**Issue by stanchan** [lucidworks/connectors-sdk-resources#55]
There seems to be limited documentation for deploying connectors as a remote instance. Would like to get some additional clarity on this type of implementation. I have changed the following values in the gradles.properties, but it doesn't seem to have any effect.

`fusionApiTarget=localhost:8765
fusionRpcTarget=localhost:8771`

Results in the following loop:
`2019-09-24T21:11:48,863 - WARN  [conn-rpc-registry-watcher-0:com.lucidworks.fusion.plugin.handler.ConnectorPluginModuleHandler@219] - {} - Service registry not ready - will try again`

Also, using an ssh tunnel doesn't seem to help either:

`2019-09-24T13:35:21,622 - ERROR [conn-rpc-registry-watcher-0:com.lucidworks.fusion.plugin.handler.ConnectorPluginModuleHandler@198] - {} - Problem discovering connector-services: Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.ConnectTimeoutException: connection timed out: /10.10.123.4:8771
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
}`

My question would what is the parameters that in the CLI that can override the previous values and how would you run the connector through a ssh tunnel?

**Comment by roblucar** [comment]
Hi @stanchan , 
From the error, it looks like Fusion's **default.address** property is not set. 
The ip added in `com.lucidworks.fusion.plugin.hosts` - needs to be the same as `default.address`

> java -Dcom.lucidworks.fusion.plugin.hosts=**52.13.47.49**:8771 -jar /fusion/4.2.4/apps/connectors/connectors-rpc/client/connector-plugin-client-4.2.4-uberjar.jar /fusion-connectors/projects/plugins/fs/build/libs/lucidworks.connector.fs-1.1.0-.zip

We will be updating the the SDK to accept remote connector connections without having to explicitly set the default.address property.  

Thanks,

**Comment by stanchan** [comment]
Setting the plugin.hosts did correct the issue. Now the plugin seems to be connecting. Output in the logs show this:
`2019-09-24T22:37:25,722 - INFO  [conn-rpc-registry-watcher-0:com.lucidworks.fusion.plugin.handler.ConnectorPluginModuleHandler$ConnectorClientChannelInstance@111] - {} - useLocalChannel=false`

What is required next to initiate the indexing of documents?

**Comment by roblucar** [comment]
Hi @stanchan  Glad to hear that worked for you. The next steps are to create a datasource then start the crawl. These steps can be scripted on the source server by leveraging datasource and scheduler apis. Hope this helps. 
Thanks

**Comment by mwmitchell** [comment]
Closing this issue for now - feel free to reopen or file a new issue if needed @stanchan
