### ISSUE TITLE
Cannot seem to get JAXWS web service to work in Fusion 4.2.2

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#84]
Hi,

We're trying to connect to a data source using a custom connector that still uses SOAP web services.  Locally, we can connect to the web service without any problems.  When we deploy it to Fusion, we are getting a NullPointerException when we try to connect to the service.  Can you let me know if there's anything specific that we should be doing to integrate JAX-WS.  We're using 2.3.0 of com.sun.xml.ws.*.

Thanks,
Eric

Here's the stack trace:
2020-08-24T10:59:30,743 - ERROR [plugin-iqvia.fusion.contentserver.content-9:connector.client.ClientMessageHandler@425] - {collectionId=EricTest, connectorType=iqvia.fusion.contentserver.content, datasourceId=cs-test, jobRunId=j9TtXqJSoU, requestId=7wNuRd0Hck} - Problem while calling client fetch()
java.lang.NullPointerException: null
	at javax.xml.ws.Service.<init>(Service.java:112) ~[?:1.8.0_151]
	at com.opentext.livelink.service.core.Authentication_Service.<init>(Authentication_Service.java:42) ~[?:?]
	at com.iqvia.fusion.connector.plugin.impl.ContentServerGenerator.authorize(ContentServerGenerator.java:35) ~[?:?]
	at com.iqvia.fusion.connector.plugin.ContentServerContentFetcher.emitCandidates(ContentServerContentFetcher.java:165) ~[?:?]
	at com.iqvia.fusion.connector.plugin.ContentServerContentFetcher.fetch(ContentServerContentFetcher.java:89) ~[?:?]
	at com.iqvia.fusion.connector.plugin.ContentServerContentFetcher.fetch(ContentServerContentFetcher.java:35) ~[?:?]
	at com.lucidworks.fusion.connector.plugin.ext.controller.ContentFetcherController.lambda$fetch$5(ContentFetcherController.java:127) ~[lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.plugin.ext.controller.AbstractFetcherController.doCall(AbstractFetcherController.java:97) ~[lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.plugin.ext.controller.ContentFetcherController.fetch(ContentFetcherController.java:118) ~[lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.plugin.ext.controller.FetchManager.lambda$doFetch$7(FetchManager.java:209) ~[lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at io.grpc.Context.call(Context.java:580) ~[grpc-context-1.15.1.jar:1.15.1]
	at com.lucidworks.fusion.connector.plugin.Logging.call(Logging.java:141) ~[connector-plugin-sdk-1.4.0-dev.12+204023d.jar:1.4.0-dev.12+204023d]
	at com.lucidworks.fusion.connector.plugin.ext.controller.FetchManager.doFetch(FetchManager.java:203) ~[lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.client.ClientMessageHandler.handleFetchReq(ClientMessageHandler.java:417) ~[lucidworks-connector-plugin-client-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.client.ClientMessageHandler.handleServerCall(ClientMessageHandler.java:166) ~[lucidworks-connector-plugin-client-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.client.ConnectorClientResponseObserver._onNext(ConnectorClientResponseObserver.java:96) ~[lucidworks-connector-plugin-client-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.client.ConnectorClientResponseObserver.lambda$onNext$2(ConnectorClientResponseObserver.java:90) ~[lucidworks-connector-plugin-client-4.2.2.jar:?]
	at io.grpc.Context.run(Context.java:565) [grpc-context-1.15.1.jar:1.15.1]
	at com.lucidworks.fusion.connector.plugin.Logging.run(Logging.java:118) [connector-plugin-sdk-1.4.0-dev.12+204023d.jar:1.4.0-dev.12+204023d]
	at com.lucidworks.fusion.connector.client.ConnectorClientResponseObserver.onNext(ConnectorClientResponseObserver.java:88) [lucidworks-connector-plugin-client-4.2.2.jar:?]
	at com.lucidworks.fusion.connector.client.ConnectorClientResponseObserver.onNext(ConnectorClientResponseObserver.java:27) [lucidworks-connector-plugin-client-4.2.2.jar:?]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at io.grpc.Context.run(Context.java:565) [grpc-context-1.15.1.jar:1.15.1]
	at com.lucidworks.fusion.connector.plugin.Logging.run(Logging.java:118) [connector-plugin-sdk-1.4.0-dev.12+204023d.jar:1.4.0-dev.12+204023d]
	at com.lucidworks.fusion.connector.plugin.ext.logging.wrappers.RunnableMDC.run(RunnableMDC.java:32) [lucidworks-connector-plugin-ext-4.2.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by eborisowIQVIA** [comment]
Switched to Apache CXF and now it's working fine.

**Comment by eborisowIQVIA** [comment]
Switched connector to Apache and it's working fine.
